# execute with
  # docker compose --profile dev up --build
services:

  ts-ui-proxy:
    image: devpatterns/ts-ui-proxy:${ENVIRONMENT:-dev}
    container_name: ts-ui-proxy
    build: ./nginx
    expose:
      - "80"
    ports:
      - "8020:80"
    profiles:
      - development
      - testing
      - production
    networks:
      - ts-ui-proxy
      - ts-ui-server

  ts-ui-server:
    env_file:
    - .env
    image: devpatterns/ts-ui-server:${ENVIRONMENT:-dev}
    container_name: ts-ui-server
    build:
      context: ./stream_view
      args:
        BUILD_ENV: ${BUILD_ENV:-development}
    ports:
      - ":8050"
    profiles:
      - development
      - testing
      - production
    networks:
    - ts-ui-server

networks:
  # For exposed API network.
  ts-ui-proxy:
    name: ts-ui-proxy
    driver: bridge
    external: false
  ts-ui-server:
    name: ts-ui-server
    driver: bridge
    external: false