apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-ui-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ts-ui-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ts-ui-server
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: ts-ui-server-env
          image: docker.io/devpatterns/stream_view:d2189a69f9c6d2b98237150a80c1300bfce0881e
          imagePullPolicy: Always
          name: ts-ui-server
          ports:
            - containerPort: 8050
              protocol: TCP
      imagePullSecrets:
        - name: dockerhub-credentials
      restartPolicy: Always