apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-ui-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ts-ui-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ts-ui-server
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: ts-ui-server-env
          image: docker.io/devpatterns/stream_view:3af9fd3a3b874d0b56c9da6709bfa7d8f82c90d2
          imagePullPolicy: Always
          name: ts-ui-server
          ports:
            - containerPort: 8050
              protocol: TCP
      imagePullSecrets:
        - name: dockerhub-credentials
      restartPolicy: Always